server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavCoder22/microservices-config-github.git # Cambia esta URL por la URL de tu repositorio
          searchPaths: config
          clone-on-start: true
      label: main  # Rama principal del repositorio

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
