spring:
  application:
    name: microservice-gateway
  cloud:
    config:
      uri: http://localhost:8888
      name: microservice-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
