spring:
  aplication:
    name: msvc-impresoras
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/impresoras
    username: root
    password: Abue2679522
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql