spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      name: microservice-eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
